// packages/@wterm/react/src/Terminal.tsx
import {
  useRef,
  useCallback,
  useImperativeHandle,
  useLayoutEffect,
  forwardRef,
  type HTMLAttributes,
} from "react";
import { WTerm, type TerminalCore } from "@wterm/dom";

// onResize and onError are omitted from HTMLAttributes because we redefine
// them with different signatures (terminal dimensions / WASM init errors).
export interface TerminalProps extends Omit<
  HTMLAttributes<HTMLDivElement>,
  "onResize" | "onError"
> {
  cols?: number;
  rows?: number;
  /**
   * A pre-constructed terminal core. When provided, `wasmUrl` is ignored and
   * this core is used instead of loading the built-in Zig WASM binary.
   */
  core?: TerminalCore;
  wasmUrl?: string;
  theme?: string;
  autoResize?: boolean;
  /** Maximum rendered Kitty image width in CSS pixels. */
  maxImageWidth?: number;
  /** Maximum rendered Kitty image height in CSS pixels. */
  maxImageHeight?: number;
  /** Force blinking on/off; omit to follow the terminal application's request. */
  cursorBlink?: boolean;
  /** Enable debug mode (init-only — changing after mount has no effect). */
  debug?: boolean;
  onData?: (data: string) => void;
  onTitle?: (title: string) => void;
  onResize?: (cols: number, rows: number) => void;
  onReady?: (wt: WTerm) => void;
  onError?: (error: unknown) => void;
}

export interface TerminalHandle {
  write(data: string | Uint8Array): void;
  resize(cols: number, rows: number): void;
  focus(): void;
  readonly instance: WTerm | null;
}

const Terminal = forwardRef<TerminalHandle, TerminalProps>(function Terminal(
  {
    cols = 80,
    rows = 24,
    core,
    wasmUrl,
    theme,
    autoResize = false,
    maxImageWidth,
    maxImageHeight,
    cursorBlink,
    debug = false,
    onData,
    onTitle,
    onResize,
    onReady,
    onError,
    className,
    style,
    ...htmlProps
  }: TerminalProps,
  ref: React.ForwardedRef<TerminalHandle>,
) {
  const wtermRef = useRef<WTerm | null>(null);
  const callbacksRef = useRef({
    onData,
    onTitle,
    onResize,
    onReady,
    onError,
  });
  const autoResizeRef = useRef(autoResize);

  callbacksRef.current = { onData, onTitle, onResize, onReady, onError };
  autoResizeRef.current = autoResize;

  useImperativeHandle(ref, () => ({
    write(data: string | Uint8Array) {
      wtermRef.current?.write(data);
    },
    resize(c: number, r: number) {
      wtermRef.current?.resize(c, r);
    },
    focus() {
      wtermRef.current?.focus();
    },
    get instance() {
      return wtermRef.current;
    },
  }));

  // React 19 callback ref with cleanup — replaces useEffect for
  // imperative, non-React library init that requires a DOM element.
  const containerRef = useCallback(
    (el: HTMLDivElement | null) => {
      if (!el) return;

      const wt = new WTerm(el, {
        cols,
        rows,
        core,
        wasmUrl,
        autoResize: autoResizeRef.current,
        maxImageWidth,
        maxImageHeight,
        cursorBlink,
        debug,
        onData: callbacksRef.current.onData
          ? (data: string) => callbacksRef.current.onData?.(data)
          : undefined,
        onTitle: (title: string) => callbacksRef.current.onTitle?.(title),
        onResize: (c: number, r: number) =>
          callbacksRef.current.onResize?.(c, r),
      });

      wtermRef.current = wt;

      wt.init()
        .then(() => {
          callbacksRef.current.onReady?.(wt);
        })
        .catch((err: unknown) => {
          if (callbacksRef.current.onError) {
            callbacksRef.current.onError(err);
          } else {
            console.error(err);
          }
        });

      return () => {
        wt.destroy();
        wtermRef.current = null;
      };
    },
    // Re-run when the WASM source or image sizing options change
    // eslint-disable-next-line react-hooks/exhaustive-deps
    [core, wasmUrl, maxImageWidth, maxImageHeight],
  );

  // Sync props to the existing instance (render-time checks)
  const wt = wtermRef.current;
  if (wt?.bridge) {
    if (!autoResizeRef.current && (wt.cols !== cols || wt.rows !== rows)) {
      wt.resize(cols, rows);
    }
    if (onData && !wt.onData) {
      wt.onData = (data: string) => callbacksRef.current.onData?.(data);
    } else if (!onData && wt.onData) {
      wt.onData = null;
    }
  }

  // Update individual classes after React commits so blink changes preserve
  // the focus and scrollback classes managed by WTerm.
  useLayoutEffect(() => {
    const el = wtermRef.current?.element;
    el?.classList.toggle("cursor-blink", cursorBlink === true);
    el?.classList.toggle("cursor-steady", cursorBlink === false);
  });

  const themeClass = theme ? `theme-${theme}` : "";
  const classes = ["wterm", themeClass, className].filter(Boolean).join(" ");

  const mergedStyle: React.CSSProperties = {
    ...(autoResize ? undefined : { height: rows * 17 + 24 }),
    ...style,
  };

  return (
    <div
      ref={containerRef}
      className={classes || undefined}
      style={mergedStyle}
      role="textbox"
      aria-label="Terminal"
      aria-multiline="true"
      aria-roledescription="terminal"
      {...htmlProps}
    />
  );
});

export default Terminal;

// packages/@wterm/svelte/src/lib/Terminal.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import type { SvelteHTMLElements } from "svelte/elements";
  import { WTerm, type TerminalCore } from "@wterm/dom";

  type DivAttributes = SvelteHTMLElements["div"];

  export interface TerminalProps
    extends Omit<DivAttributes, "onresize"> {
    /** Column count. */
    cols?: number;
    /** Row count. */
    rows?: number;
    /**
     * A pre-constructed terminal core. When provided, `wasmUrl` is ignored and
     * this core is used instead of loading the built-in Zig WASM binary.
     */
    core?: TerminalCore;
    /** Optional override for the WASM binary URL used by the terminal core. */
    wasmUrl?: string;
    /** Theme name appended as a `theme-<name>` class on the root element. */
    theme?: string;
    /**
     * When `true`, the terminal observes its container and reflows on size
     * changes. Defaults to `false` for framework wrappers.
     */
    autoResize?: boolean;
    /** Maximum rendered Kitty image width in CSS pixels. */
    maxImageWidth?: number;
    /** Maximum rendered Kitty image height in CSS pixels. */
    maxImageHeight?: number;
    /** Toggles the `cursor-blink` class on the root element. */
    cursorBlink?: boolean;
    /** Enable debug mode (init-only — changing after mount has no effect). */
    debug?: boolean;
    /** Called when the terminal produces input data. */
    onData?: (data: string) => void;
    /** Called when the terminal title changes via an escape sequence. */
    onTitle?: (title: string) => void;
    /** Called after the terminal is resized. */
    onResize?: (cols: number, rows: number) => void;
    /** Called once after `WTerm.init()` resolves. */
    onReady?: (wt: WTerm) => void;
    /** Called if WASM loading or initialization fails. */
    onError?: (error: unknown) => void;
  }

  let {
    cols = 80,
    rows = 24,
    core,
    wasmUrl,
    theme,
    autoResize = false,
    maxImageWidth,
    maxImageHeight,
    cursorBlink = false,
    debug = false,
    onData,
    onTitle,
    onResize,
    onReady,
    onError,
    class: className = "",
    style,
    ...rest
  }: TerminalProps = $props();

  let root: HTMLDivElement;
  let current: WTerm | null = $state(null);

  export function write(data: string | Uint8Array) {
    current?.write(data);
  }

  export function resize(nextCols: number, nextRows: number) {
    current?.resize(nextCols, nextRows);
  }

  export function focus() {
    current?.focus();
  }

  export function instance() {
    return current;
  }

  const classes = $derived(
    ["wterm", theme ? `theme-${theme}` : null, className]
      .filter(Boolean)
      .join(" "),
  );

  const mergedStyle = $derived.by(() => {
    if (autoResize) return style;
    const fixedHeight = `height: ${rows * 17 + 24}px`;
    return style ? `${fixedHeight}; ${style}` : fixedHeight;
  });

  onMount(() => {
    const wt = new WTerm(root, {
      cols,
      rows,
      core,
      wasmUrl,
      autoResize,
      maxImageWidth,
      maxImageHeight,
      cursorBlink,
      debug,
      onData: onData ? (data: string) => onData?.(data) : undefined,
      onTitle: (title: string) => onTitle?.(title),
      onResize: (nextCols: number, nextRows: number) =>
        onResize?.(nextCols, nextRows),
    });

    current = wt;

    wt.init()
      .then(() => {
        onReady?.(wt);
      })
      .catch((err: unknown) => {
        if (onError) {
          onError(err);
        } else {
          console.error(err);
        }
      });

    return () => {
      wt.destroy();
      if (current === wt) current = null;
    };
  });

  $effect(() => {
    const wt = current;
    if (
      wt?.bridge &&
      !autoResize &&
      (wt.cols !== cols || wt.rows !== rows)
    ) {
      wt.resize(cols, rows);
    }
  });

  $effect(() => {
    current?.element.classList.toggle("cursor-blink", cursorBlink);
  });

  $effect(() => {
    const wt = current;
    if (!wt) return;
    wt.onData = onData ? (data: string) => onData?.(data) : null;
  });
</script>

<div
  {...rest}
  bind:this={root}
  class={classes || undefined}
  style={mergedStyle}
  role="textbox"
  aria-label="Terminal"
  aria-multiline="true"
  aria-roledescription="terminal"
></div>
